name: "Create MantisHub Version"
description: "An action to create version in MantisHub"
inputs:
  url:
    description: "Base URL of the MantisHub API"
    required: true
  api-key:
    description: "API key for authentication"
    required: true
  project-id:
    description: "Project ID"
    required: true
  name:
    description: "Name of the version"
    required: true
  description:
    description: "Description of the version"
    required: true
  released:
    description: "Flag for released e.g true/false"
    required: true
  obsolete:
    description: "Flag for released e.g true/false"
    required: true
  timestamp:
    description: "Date of the release eg. YYYY-MM-DD"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Issue in MantisHub
      shell: bash
      run: |
        curl --location "${{ inputs.url }}/api/rest/projects/${{ inputs.project-id }}/versions" \
          --header "Authorization: ${{ inputs.api-key }}" \
          --header 'Content-Type: application/json' \
          --data '{
            "name": "${{ inputs.name }}",
            "description": "${{ inputs.description }}",        
            "released": "${{ inputs.released }}",
            "obsolete": "${{ inputs.obsolete }}",
            "timestamp": "${{ inputs.timestamp }}"
          }'
branding:
  color: "green"
  icon: "check"
