name: "Create MantisHub Issue"
description: "An action to create issues in MantisHub"
inputs:
  url:
    description: "Base URL of the MantisHub API"
    required: true
  api-key:
    description: "API key for authentication"
    required: true
  project-id:
    description: "Project ID or name"
    required: true
  summary:
    description: "Summary of the issue"
    required: true
  description:
    description: "Description of the issue"
    required: true
  category:
    description: "Category of the issue"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Issue in MantisHub
      shell: bash
      run: |
        curl --location "${{ inputs.url }}/api/rest/issues" \
          --header "Authorization: ${{ inputs.api-key }}" \
          --header 'Content-Type: application/json' \
          --data '{
            "project": { "id": "${{ inputs.project-id }}" },
            "summary": "${{ inputs.summary }}",
            "description": "${{ inputs.description }}",
            "category": { "name": "${{ inputs.category }}" }
          }'
branding:
  color: "green"
  icon: "bug"
