name: "MantisHub Actions"
description: "MantisHub actions for creating issues and versions"
author: "Salman Shafiq"
inputs:
  task:
    description: 'Task to perform e.g create-issue or create-version'
    required: true
  url:
    description: 'Base URL of the MantisHub API'
    required: true
  api-key:
    description: 'API key for authentication'
    required: true
  project:
    description: 'Project name in MantisHub'
    required: true


runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: 'activity'
  color: 'green'
