name: "Create MantisHub Version"
description: "An action to create versions in MantisHub"

inputs:
  url:
    description: "Base URL of the MantisHub API"
    required: true
  api-key:
    description: "API key for authentication"
    required: true
  project:
    description: "Project Name"
    required: true
  name:
    description: "Name of the version"
    required: true
  description:
    description: "Description of the version"
    required: false
  released:
    description: "Set to true if the version is released"
    required: false
  obsolete:
    description: "Set to true if the version is obsolete"
    required: false
  timestamp:
    description: "Release date of the version"
    required: false

runs:
  using: "node16"
  main: "../../dist/index.js"
